version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:4000
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - ./api/uploads:/app/uploads
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
volumes:
  minio-data:
